# Generated by Django 4.0.4 on 2022-10-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_armors_computers_crewquarters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thrusters',
            old_name='thurster',
            new_name='thruster',
        ),
    ]
