# Generated by Django 4.0.4 on 2022-10-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_thurster_thrusters_thruster'),
    ]

    operations = [
        migrations.AddField(
            model_name='armors',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
