# Generated by Django 4.0.4 on 2022-10-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_armors_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='driftengines',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
