# Generated by Django 4.0.4 on 2022-10-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_driftengines_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelWeapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(max_length=48)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='security',
            name='cost',
            field=models.CharField(max_length=36),
        ),
    ]
