# Generated by Django 4.0.4 on 2022-10-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_personnelweapons_alter_security_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelWeaponsLongarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(max_length=48)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='PersonnelWeapons',
            new_name='PersonnelWeaponsHeavy',
        ),
    ]
