# Generated by Django 4.0.4 on 2022-10-27 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_customselect_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customselect',
            name='armor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.armors'),
        ),
        migrations.AlterField(
            model_name='customselect',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.computers'),
        ),
        migrations.AlterField(
            model_name='customselect',
            name='crewQuarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.crewquarters'),
        ),
        migrations.AlterField(
            model_name='customselect',
            name='defensiveCountermasure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.defensivecountermeasures'),
        ),
        migrations.AlterField(
            model_name='customselect',
            name='driftEngine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.driftengines'),
        ),
        migrations.AlterField(
            model_name='customselect',
            name='expansionBay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.expansionbays'),
        ),
        migrations.AlterField(
            model_name='customselect',
            name='powercore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.powercores'),
        ),
        migrations.AlterField(
            model_name='customselect',
            name='security',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.security'),
        ),
        migrations.AlterField(
            model_name='customselect',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.sensors'),
        ),
        migrations.AlterField(
            model_name='customselect',
            name='shield',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.shields'),
        ),
        migrations.AlterField(
            model_name='customselect',
            name='thruster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.thrusters'),
        ),
        migrations.AlterField(
            model_name='customselect',
            name='weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.weapons'),
        ),
    ]
