# Generated by Django 4.0.4 on 2022-10-27 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_customselect_armor_alter_customselect_computer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customselect',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.computers'),
        ),
        migrations.AlterField(
            model_name='customselect',
            name='crewQuarter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.crewquarters'),
        ),
        migrations.AlterField(
            model_name='customselect',
            name='driftEngine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.driftengines'),
        ),
        migrations.AlterField(
            model_name='customselect',
            name='powercore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.powercores'),
        ),
        migrations.AlterField(
            model_name='customselect',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.sensors'),
        ),
        migrations.AlterField(
            model_name='customselect',
            name='thruster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.thrusters'),
        ),
    ]
